### PR TITLE
(Feature) Make Validators DApp display company info for xDai Network

### PR DESCRIPTION
**Pull request by varasev**
**(Mandatory) Description**

This PR solves the issue https://github.com/poanetwork/poa-dapps-validators/issues/96. Should only be merged after https://github.com/poanetwork/poa-network-consensus-contracts/pull/204 is merged and the new `ValidatorMetadata` contract is deployed into `xDai network`. These changes are compatible with the current `ValidatorMetadata` contracts in `Core` and `Sokol` networks. After merging this PR, please merge https://github.com/poanetwork/poa-test-setup/pull/58.

The validator's card for a company will look like this:

image

The `Set Metadata` page is complemented with notary/company switcher which will only be available for xDai Network:

image

If the validator chooses `I'm a company`, the `Set Metadata` page looks like this:

image

**(Mandatory) What is it: (Fix), (Feature), or (Refactor)**
(Feature)

### CODE REVIEW

**Comment by varasev** [comment]
@pashagonchar do you have any idea how we could repaint the icon for a company? That's how it looks at the moment: https://github.com/poanetwork/poa-dapps-validators/blob/6fcfe427d44363726a7fc43035cf79e6bdd3ed92/src/images/icons/icon-company.svg

I just copied this from https://github.com/poanetwork/poa-dapps-validators/blob/6fcfe427d44363726a7fc43035cf79e6bdd3ed92/src/images/icons/icon-notary-license.svg

**Comment by varasev** [comment]
The new implementation of `ValidatorMetadata` contract has been applied in `xDai network`: https://blockscout.com/poa/dai/address/0x61e561dc17597b15e0195a201b539ee7b9add3ff. So now we can merge this PR.

The new implementation address of `ValidatorMetadata` can be checked on the page of a proxy contract: https://blockscout.com/poa/dai/address/0xeb35547e1e4630fc6ed9a6f3d4c5e436422f63ea/read_contract

**Review by vbaranov — CHANGES_REQUESTED** [review]
1. screen shot 2018-12-17 at 15 16 12
2. There is no validation on email field, that email is valid. https://www.npmjs.com/package/email-validator

**Comment by varasev** [comment]
Fixed in https://github.com/poanetwork/poa-dapps-validators/pull/98/commits/ba40d599c5572e546c550b9828fd085994b9ced0.

**Review by vbaranov — CHANGES_REQUESTED** [review]
screen shot 2018-12-17 at 17 53 45

**Comment by varasev** [comment]
@vbaranov Sorry, didn't check that for the empty set of data. Fix: https://github.com/poanetwork/poa-dapps-validators/pull/98/commits/c941588d5952456652bc8a433f6e18b614f9610d.

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
