### PR TITLE
Make view responsive

### PR DESCRIPTION
**Pull request by ghost**
Problem:
current layout doesn't support responsive layout. Mobile clients see desktop version.
Solution:
add the responsive layout.

Problem:
Default ```node sass``` compiler compiles two files (index & changed) files
Solution:
Add ```nodemon``` watcher to watch ```.scss``` files. Do not forget ```npm istall``` before using

### CODE REVIEW

**Comment by rstormsf** [comment]
@Dobriy-i 
I can't approve this PR for the following reasons:
1. It was fork off 
https://github.com/poanetwork/poa-dapps-validators/commit/1eb84b960143cff3045ed8e6ff23f7f95f2a3457
this commit which is already old and there are quite a few conflicting changes
Please rebase your work with latest `core` branch commit and add a new commit to this PR

2. Commit missing `package-lock.json` file
3. Provide a description for this PR, example: adding a new `nodemon` module. Why? 
and advice developers to re-run `npm install` 
4. Don't commit directly to the main repo, please fork off your own under your own github name and submit PR from your own repo to this repo

**Comment by ghost** [comment]
@rstormsf i've resolved all conflicts, please check again. About description's question, where should i provide it? here? About fork, let's finish this pull request here, next time i'll work through the fork

**Comment by igorbarinov** [comment]
@Dobriy-i I've added a description. Next time please use Problem/Solution or List of features approach. Our policy for PRs https://github.com/poanetwork/RFC/issues/3

**Comment by ghost** [comment]
@igorbarinov i see. @rstormsf i've also added a description to the first post, about ```nodemon``` so up to you next

**Comment by rstormsf** [comment]
@Dobriy-i 
there is bug in header
image

**Comment by rstormsf** [comment]
also @Dobriy-i the color is not chaning in header in Sokol

**Comment by ghost** [comment]
Fixed indent. The color won't be changed because it is image, if you want we can remove it and use plain color for sokol

**Comment by rstormsf** [comment]
@Dobriy-i please remove the image and use plain color

**Comment by ghost** [comment]
done

**Review by rstormsf — APPROVED** [review]

**Pull request merged**
