### PR TITLE
(Feature) Add support for the Kovan testnet

### PR DESCRIPTION
**Pull request by varasev**
- (Mandatory) Description
These changes add support for the Kovan network. UI colors and logo have been copied from Sokol styles.

- (Mandatory) What is it: (Fix), (Feature), or (Refactor) in Title
(Feature)

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@varasev could you add a screenshot of a view of dapp when it is connected to Kovan to PR?

**Comment by varasev** [comment]
The screen:

image

**Review by vbaranov — COMMENTED** [review]
`Sokol` and `Kovan` have the same styles in this PR. Is it possible to visually distinguish them? For example, as we have done in BlockScout:

1. Here is the logo for Kovan https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/kovan_logo.svg
2. main colour: `#6ac9b9` => `#28aca4`
3. secondary colour: https://github.com/poanetwork/poa-dapps-validators/blob/a0b772bf97db20c64edbded67283b8b18ff89b4b/src/assets/stylesheets/helpers/_variables.scss#L18 => `#1f857f`

**Comment by varasev** [comment]
Ok, done:

image

**Review by vbaranov — APPROVED** [review]

**Comment by varasev** [comment]
As for the logo: I'd propose to leave Sokol's logo - it looks better, imho.

**Comment by varasev** [comment]
Don't merge these PRs, please. Let's wait until Kovan HF is done.

**Comment by vbaranov** [comment]
Sure, please merge them when you are ready.

**Comment by pashagonchar** [comment]
@varasev @vbaranov 

https://zpl.io/VkpzXPK

kovan_logo

**Comment by varasev** [comment]
@pashagonchar Thanks! Could you attach SVG here?

**Comment by pashagonchar** [comment]
@varasev 


[logos.zip](https://github.com/poanetwork/poa-dapps-validators/files/3128055/logos.zip)

**Comment by varasev** [comment]
@pashagonchar Please also attach the logo for the loading screen. For Kovan it looks like this at the moment:

image

SVG is here: https://github.com/poanetwork/poa-dapps-validators/blob/kovan-network/src/components/Loading/kovan.svg

**Comment by pashagonchar** [comment]
@varasev 

[kovan-logo.svg.zip](https://github.com/poanetwork/poa-dapps-validators/files/3147118/kovan-logo.svg.zip)

**Pull request merged**
