### PR TITLE
(Feature) Restyling

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
**- Description:**

I was asked to do a facelift for the Validators DApp.

There were no designs provided, so the restyling had to be done taking the POA Network Bridge UI and the POA Network style guide as guidelines.

**- What is it:** (Feature)

**What to expect visually from this update:**

Loading Screen (desktop / tablet / phone):

loading desktop

loading tablet

loading phone

Header and contents from the "All" section  (desktop / tablet / phone):

all desktop

all tablet

all phone

Mobile menu:

mobile menu

Header and Footer (desktop / tablet / phone):

header footer desktop

header footer tablet

header footer mobile

Set metadata (desktop / tablet / phone):

set metadata desktop

set metadata tablet

set metadata mobile

**Notes:**

1- There are also alternatives for the DApp's Sokol version, for example:

screen shot 2018-07-16 at 15 12 58
screen shot 2018-07-16 at 15 13 07

### CODE REVIEW

**Comment by pashagonchar** [comment]
poa_validators_1
poa_validators_2

**Comment by pashagonchar** [comment]
Zeplin:
https://zpl.io/ad76B3K - All
https://zpl.io/anK5GNk - Set Metadata

**Comment by varasev** [comment]
Could you rename "Address..." label in the search field to "Search..." because searching works not only by address.

**Comment by gabitoesmiapodo** [comment]
@pashagonchar Applied visual changes, based on the Zeplin designs.

@varasev Fixed.

Now you should see something like this:

screen shot 2018-07-18 at 14 20 32
screen shot 2018-07-18 at 14 20 42
screen shot 2018-07-18 at 14 20 50

screen shot 2018-07-18 at 14 18 05
screen shot 2018-07-18 at 14 18 16
screen shot 2018-07-18 at 14 18 27

**Comment by pablofullana** [comment]
Live version updated at: http://poa-validators-restyle.herokuapp.com/

**Comment by varasev** [comment]
@vbaranov I've checked restyled Validators DApp on a local test setup - everything works fine. I'm still not approving this because we should fix the issue https://github.com/poanetwork/poa-test-setup/issues/39 before. I'm working on that.

**Review by vbaranov — COMMENTED** [review]
@gabitoesmiapodo 

screen shot 2018-07-20 at 15 26 50


maybe, something like this?

**Comment by varasev** [comment]
https://github.com/poanetwork/poa-test-setup/issues/39 was fixed and tested. So, I think we could approve this PR. @vbaranov should we solve https://github.com/poanetwork/poa-test-setup/issues/38 before merging this PR? What do you think?

**Comment by gabitoesmiapodo** [comment]
@vbaranov Done.

desktop
tablet
mobile
mobile 2

**Review by varasev — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
