### PR TITLE
(Feature) Display an index of each validator

### LINKED ISSUE #42: (problem) show total number of validators
Solution: display somewhere current total number of validators 
also display on each validator the index in the array of validators

### PR DESCRIPTION
**Pull request by varasev**
- (Mandatory) Description
Displaying an index of each validator in the list. Relates to https://github.com/poanetwork/poa-dapps-validators/issues/42.

- (Mandatory) What is it: (Fix), (Feature), or (Refactor) in Title
(Feature)

Closes #42

### CODE REVIEW

**Comment by vbaranov** [comment]
@varasev could you post a screenshot how it will look like in UI?

**Comment by varasev** [comment]
It looks like this now:

image

**Review by vbaranov — CHANGES_REQUESTED** [review]
We don't need to show index in Pending changes section, or at least index should be the same as for the same address in "All" section:
screen shot 2018-06-12 at 16 30 48

**Comment by varasev** [comment]
Got it. Will be fixed.

**Comment by varasev** [comment]
Displaying of the index has been removed from `Pending changes` tab:  https://github.com/varasev/poa-dapps-validators/commit/8d3b2821f4732446c95499f253e5ba124047bb3d

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
